### ISSUE TITLE
Cleaner code (Do not Repeat Yourself)

### ISSUE THREAD

**Issue by GabrieleVir** [GabrieleVir/projet-12-MVC#2]
Polish the code to have less views pages and less controllers.

**Comment by GabrieleVir** [comment]
Any advice are welcome!

**Comment by pixeline** [comment]
The answer lies in how you design your system to solve the problem at hand.
In this case (a very simple problem), I would assume that it could work to have only one class (for example: "Website" or "Page" ), with one method per page :-)

**Comment by GabrieleVir** [comment]
At the end, I chose to use a class for every single pages. 
It helps me to read my code and for the flexibility it provides. If I want to modify a specific page, I can create methods inside their class and if there is a problem, I know where to look. 
Thank you again for the feedback and advice!
