### ISSUE TITLE
Normalise the casing of your file names

### ISSUE THREAD

**Issue by pixeline** [GabrieleVir/projet-12-MVC#3]
Careful : some linux distros are case insensitive, other are case sensitive.
So it's a best practice to write always using lowercase everywhere (file, folders)...

**Comment by GabrieleVir** [comment]
For the class names, is it better to change it too?

**Comment by pixeline** [comment]
You mean inside the files ? Nope! My comment is only for file names ("filenames.php" instead of "Filenames.php").  =)

**Comment by GabrieleVir** [comment]
Done! Thanks for your advice!
